# Generated by Django 4.1.1 on 2022-09-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.DecimalField(decimal_places=3, max_digits=10)),
                ("describtion", models.TextField()),
                ("img", models.ImageField(upload_to="photos/%y/%m/%d")),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
