# Generated by Django 4.1.1 on 2022-09-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car", options={"ordering": ["name", "price"], "verbose_name": "Car"},
        ),
        migrations.AddField(
            model_name="car",
            name="color",
            field=models.CharField(
                choices=[("red", "Red"), ("black", "Black"), ("White", "White")],
                default="Not Selected",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="describtion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="car",
            name="img",
            field=models.ImageField(
                upload_to="photos/%y/%m/%d", verbose_name="picture"
            ),
        ),
    ]
