# Generated by Django 4.1.1 on 2022-09-28 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_car_options_car_color_alter_car_describtion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="datetime_added",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 9, 28, 13, 53, 27, 229570)
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(
                choices=[
                    ("not selected", "Not Selected"),
                    ("red", "Red"),
                    ("black", "Black"),
                    ("White", "White"),
                ],
                default="Not Selected",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
