# Generated by Django 4.1.1 on 2022-09-29 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_car_datetime_added_alter_car_color_alter_car_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="datetime_added",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 9, 29, 9, 50, 19, 853517)
            ),
        ),
    ]
